name: Changelog Updated
on:
  pull_request:
    types: edited

jobs:
  pr_body_edited_job:
    runs-on: ubuntu-latest
    if: |
      github.event.changes.body &&
      contains(github.event.pull_request.labels.*.name, 'version-update') &&
      github.event.pull_request.state == 'open'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Fetch and merge changes
      #   run: |
      #     git fetch origin
      #     git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Print new contents
        run: |
          java -Dfile.encoding=UTF-8 -jar modpackUpdater.jar
          git add changelogs.json
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "Updated changelogs.json"
          git push origin HEAD:${{ github.head_ref }}
        env:
          CHANGELOG: ${{ github.event.pull_request.body }}