name: Update version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: ''
jobs:
  updateVersionFile:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Output dir
        run: ls
      - name: Update File
        run: java -Dfile.encoding=UTF-8 -jar modpackUpdater.jar
        env: 
          VERSION: ${{ inputs.version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: '[Bot] Update to ${{ inputs.version }}'
          labels: |
              version-update
          body: |
            Replace my contents with the changelog
          branch: |
            changelog/${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.version }}